import { ArrowDownRight, ArrowUpRight, Check, MoveUpRight, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { products, sectors, services } from "@/lib/catalogue";
import { PageFrame, Eyebrow, SectionHeading } from "@/components/SiteShell";
import { VideoShowcase } from "@/components/VideoShowcase";
import { trpc } from "@/lib/trpc";

export default function Home() {
  const productsQuery = trpc.content.products.useQuery();
  const activeProducts = productsQuery.data ?? products;
  const featured = activeProducts.slice(0, 4);
  const settingsQuery = trpc.content.settings.useQuery();
  const heroSlidesQuery = trpc.content.heroSlides.useQuery();
  const siteSettings = settingsQuery.data ?? {};
  const heroSlides = heroSlidesQuery.data ?? [];
  const [activeSlide, setActiveSlide] = useState(0);
  useEffect(() => {
    if (heroSlides.length < 2) return;
    const timer = window.setInterval(() => setActiveSlide(current => (current + 1) % heroSlides.length), 6000);
    return () => window.clearInterval(timer);
  }, [heroSlides.length]);
  const currentSlide = heroSlides[activeSlide];
  const heroTitle = currentSlide?.title || siteSettings.home_hero_title;
  const heroHeading = heroTitle ? heroTitle.split(/(inspire)/gi).map((part, index) => part.toLowerCase() === "inspire" ? <em key={index}>{part}</em> : part) : <>La propreté qui <em>inspire</em> confiance.</>;
  return <PageFrame>
    <section className="hero-section"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="container hero-grid"><div className="hero-copy"><Eyebrow light>{currentSlide?.eyebrow || "Hygiène professionnelle · Tunisie"}</Eyebrow><h1>{heroHeading}</h1><p>{currentSlide?.subtitle || siteSettings.home_hero_text || "CAN LIGNE BLEUE accompagne les entreprises avec des produits, équipements et solutions de nettoyage conçus pour les environnements qui ne laissent rien au hasard."}</p><div className="hero-actions"><Link href={currentSlide?.ctaUrl || "/products"} className="button button-light">{currentSlide?.ctaLabel || "Découvrir nos produits"} <ArrowUpRight size={17} /></Link><Link href="/devis" className="button button-ghost-light">Demander un devis <ArrowUpRight size={17} /></Link></div><div className="hero-proof"><div className="proof-item"><strong>{activeProducts.length}+</strong><span>références<br />sélectionnées</span></div><div className="proof-divider" /><div className="proof-item"><strong>B2B</strong><span>solutions pour<br />professionnels</span></div></div></div><div className="hero-visual"><div className="hero-panel"><div className="hero-panel-label">{currentSlide?.eyebrow || "Sélection professionnelle"} <span>{String(activeSlide + 1).padStart(2, "0")} / {String(Math.max(heroSlides.length, 1)).padStart(2, "0")}</span></div><img src={currentSlide?.imageUrl || siteSettings.home_hero_image_url || activeProducts[4]?.image || products[4].image} alt={currentSlide?.title || "Solution professionnelle"} /><div className="hero-product-tag"><span className="status-dot" /><div><strong>{currentSlide?.title || "DENGRAS"}</strong><small>{currentSlide?.subtitle || "Dégraissant haute performance"}</small></div><ArrowUpRight size={18} /></div></div><div className="hero-floating-card"><Sparkles size={17} /><span>Des solutions<br /><strong>à votre mesure</strong></span></div></div></div>{heroSlides.length > 1 && <div className="hero-slide-dots container">{heroSlides.map((slide, index) => <button key={slide.id} aria-label={`Afficher le slide ${index + 1}`} className={index === activeSlide ? "active" : ""} onClick={() => setActiveSlide(index)} />)}</div>}<div className="container hero-scroll"><span>Faire défiler</span><ArrowDownRight size={17} /></div></section>
    <section className="trust-strip"><div className="container trust-inner"><span>Une expertise construite pour</span><div className="trust-sectors"><span>HÔTELS</span><span>RESTAURANTS</span><span>BUREAUX</span><span>INSTITUTIONS</span><span>COMMERCES</span></div></div></section>
    <VideoShowcase eyebrow="L’univers CAN LIGNE BLEUE" title={<>La propreté en mouvement.<br /><span>Le geste juste, au bon moment.</span></>} text="Une future collection de clips courts montrera nos solutions en situation, dans les environnements professionnels que nous accompagnons." poster={siteSettings.video_hero_poster_url || activeProducts[1]?.image || products[1].image} videoSrc={siteSettings.video_hero_url || undefined} />
    <section className="section expertise-section container"><div className="expertise-intro"><SectionHeading eyebrow="Notre approche" title={<>Plus qu’un produit.<br /><span>Une réponse complète.</span></>} text="Nous réunissons les bons produits, la bonne méthode et la bonne écoute pour vous aider à maintenir des espaces impeccables, jour après jour." /><Link href="/about" className="text-link text-link-large">Découvrir CAN LIGNE BLEUE <ArrowUpRight size={16} /></Link></div><div className="expertise-cards"><div className="expertise-card expertise-card-dark"><span className="card-index">01</span><ShieldCheck size={28} /><h3>La fiabilité<br />comme standard</h3><p>Des références sélectionnées pour leur efficacité dans les contextes professionnels.</p></div><div className="expertise-card"><span className="card-index">02</span><Target size={28} /><h3>Le conseil<br />qui fait la différence</h3><p>Une approche claire pour répondre à vos contraintes terrain et à vos objectifs.</p></div><div className="expertise-card expertise-card-lagoon"><span className="card-index">03</span><Users size={28} /><h3>Un partenaire<br />à vos côtés</h3><p>Des échanges simples, des réponses rapides et une relation conçue pour durer.</p></div></div></section>
    <section className="section product-preview-section"><div className="container"><SectionHeading eyebrow="Catalogue produits" title={<>Des solutions professionnelles,<br /><span>sans compromis.</span></>} text="Du nettoyage quotidien aux besoins les plus exigeants, trouvez la référence adaptée à votre environnement." /><div className="preview-grid">{featured.map((product, index) => <Link href={`/products/${product.slug}`} key={product.slug} className={`preview-card ${index === 0 ? "preview-card-featured" : ""}`}><div className="preview-card-image"><img src={product.image} alt={product.name} loading="lazy" /><span className="round-arrow"><ArrowUpRight size={18} /></span></div><div className="preview-card-meta"><span>{product.category}</span><strong>{product.name}</strong></div></Link>)}</div><div className="section-cta"><Link href="/products" className="button button-secondary">Explorer tout le catalogue <ArrowUpRight size={17} /></Link></div></div></section>
    <section className="section sectors-section container"><div className="sectors-layout"><div><SectionHeading eyebrow="Solutions par secteur" title={<>Pensé pour vos<br /><span>réalités métier.</span></>} text="Chaque environnement a ses propres exigences. Notre catalogue et notre conseil s’adaptent à votre quotidien." /><Link href="/contact" className="button button-primary">Parler à un expert <ArrowUpRight size={17} /></Link></div><div className="sector-list">{sectors.map((sector, index) => <div className="sector-row" key={sector.title}><span className="sector-number">0{index + 1}</span><div><h3>{sector.title}</h3><p>{sector.detail}</p></div><MoveUpRight size={20} /></div>)}</div></div></section>
    <section className="dark-cta"><div className="container dark-cta-inner"><div><Eyebrow light>Un besoin spécifique ?</Eyebrow><h2>Construisons la bonne<br /><em>solution ensemble.</em></h2></div><Link href="/devis" className="button button-light">Démarrer une conversation <ArrowUpRight size={17} /></Link></div></section>
  </PageFrame>;
}
